import { prisma } from "../utils/prisma";
import PDFDocument from "pdfkit";

export async function downloadMinutesPdf(req: any, res: any) {
  try {
    const { meetingId } = req.params;
    const user = req.user;

    const meeting = await prisma.meeting.findUnique({
      where: { id: meetingId },
      include: { minutes: true },
    });

    if (!meeting) {
      return res.status(404).json({ message: "Meeting not found" });
    }

    // 🔐 Access Control
    const isCreator = meeting.createdBy === user.userId;
    const isAdmin = user.role === "ADMIN";

    if (meeting.visibility === "PRIVATE" && !isCreator && !isAdmin) {
      return res.status(403).json({ message: "Not allowed" });
    }

    if (!meeting.minutes) {
      return res.status(404).json({ message: "Minutes not generated" });
    }

    const minutes = meeting.minutes;

    const doc = new PDFDocument({ margin: 50 });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename=meeting-${meetingId}.pdf`
    );

    doc.pipe(res);
    // ✅ Watermark for PRIVATE / Sensitive
    if (meeting.visibility === "PRIVATE" || minutes.isSensitive) {
      doc.save();
      doc.rotate(-30, { origin: [150, 300] });
      doc.fontSize(50).fillColor("#eeeeee").text("CONFIDENTIAL", 80, 250, {
        align: "center",
      });
      doc.restore();
      doc.fillColor("black");
    }

    // ===== HEADER =====
    doc
      .fontSize(20)
      .font("Helvetica-Bold")
      .text("Minutes of Meeting", { align: "center" });

    doc.moveDown();

    if (minutes.isSensitive) {
      doc
        .fontSize(12)
        .fillColor("red")
        .text("⚠ CONFIDENTIAL – INTERNAL USE ONLY", { align: "center" })
        .fillColor("black");

      doc.moveDown();
    }

    doc
      .fontSize(12)
      .font("Helvetica")
      .text(`Title: ${meeting.title}`)
      .text(`Visibility: ${meeting.visibility}`)
      .text(`Date/Time: ${new Date(meeting.dateTime).toLocaleString()}`);

    doc.moveDown(2);

    // ===== SUMMARY =====
    doc.font("Helvetica-Bold").fontSize(14).text("Summary");
    doc.moveDown(0.5);
    doc.font("Helvetica").fontSize(11).text(minutes.mom);

    doc.moveDown(2);

    // ===== DECISIONS =====
    doc.font("Helvetica-Bold").fontSize(14).text("Decisions");
    doc.moveDown(0.5);

    (minutes.decisions as string[]).forEach((d) => {
      doc.font("Helvetica").fontSize(11).text(`• ${d}`);
    });

    doc.moveDown(2);

    // ===== ACTION ITEMS =====
    doc.font("Helvetica-Bold").fontSize(14).text("Action Items");
    doc.moveDown(0.5);

    (minutes.actionItems as any[]).forEach((a) => {
      doc
        .font("Helvetica")
        .fontSize(11)
        .text(
          `• ${a.task} | Assignee: ${a.assignee || "-"} | Due: ${
            a.dueDate || "-"
          }`
        );
    });

    doc.moveDown(2);

    // ===== METADATA =====
    doc.font("Helvetica-Bold").fontSize(14).text("Metadata");
    doc.moveDown(0.5);

    doc
      .font("Helvetica")
      .fontSize(11)
      .text(`Tags: ${minutes.tags.join(", ")}`)
      .text(`Sensitive: ${minutes.isSensitive ? "Yes" : "No"}`)
      .text(`Reason: ${minutes.sensitivityReason || "None"}`);

    doc.moveDown(3);

    // ===== FOOTER =====
    doc
      .fontSize(9)
      .fillColor("gray")
      .text(
        "Generated by AI Meeting Intelligence Engine",
        { align: "center" }
      );

    doc.end();

    const docId = `MOM-${meeting.id.slice(0, 8)}-${minutes.id.slice(0, 8)}`;

    doc.moveDown(2);
    doc.fontSize(9).fillColor("gray").text(
      `Doc ID: ${docId}  |  Generated By: ${user.userId}  |  Generated At: ${new Date().toLocaleString()}`,
      { align: "center" }
    );
    doc.fillColor("black");

  } catch (err: any) {
    return res.status(500).json({
      message: err.message || "PDF generation failed",
    });
  }
}
