ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'CEO';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'CHAIRMAN';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'HR';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'FACULTY';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'CORESPONDANT';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'FOUNDER';
